spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/community
    username: sa
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths:
      -  src/main/java
      
      exclude: WEB-INF/**
      
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
    